{% set name = "chaco" %}
{% set version = "5.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../chaco/

build:
  # string: 4a6683_2
  number: 1
  # script: python setup.py install  --single-version-externally-managed --record=record.txt
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    # - setuptools
    - vs2019_win-64
    # - {{compiler('c')}}
    # - {{compiler('cxx')}}
    - git
    - cmake
  
  host:
    - python
    - enable =5.2.1
    - Cython
    - importlib_resources

  run:
    # - python
    - enable =5.2.1
    # - cython
    - importlib_resources

test:
  # Python imports
  imports:
    - chaco
    - chaco.api
    # - chaco.contour
    # - chaco.downsample
    # - chaco.downsample.tests
    # - chaco.layers
    # - chaco.overlays
    # - chaco.plugin
    # - chaco.scales
    # - chaco.scales.tests
    # - chaco.shell
    # - chaco.tests
    # - chaco.tools
    # - chaco.tools.tests
    # - chaco.tools.toolbars
    - chaco.ui

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docs.enthought.com/chaco
  license: BSD License
  summary: 'interactive 2-dimensional plotting'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

extra:
  recipe-maintainers:
    - capn-freako
